name: Deploy Terminal Portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Trigger when resume repository is updated (requires webhook setup)
  repository_dispatch:
    types: [resume-updated]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Fetch resume and build
        env:
          # Configure your resume repository here or set in repository variables
          VITE_RESUME_REPO: ${{ vars.RESUME_REPO || 'ahzs645/resume' }}
          VITE_RESUME_BRANCH: ${{ vars.RESUME_BRANCH || 'main' }}
          VITE_RESUME_FILE_PATH: ${{ vars.RESUME_FILE_PATH || 'Ahmad_Jalil_CV.yaml' }}
          VITE_RESUME_PDF_PATH: ${{ vars.RESUME_PDF_PATH || 'Ahmad_Jalil_CV.pdf' }}
          VITE_USE_LOCAL_FALLBACK: ${{ vars.USE_LOCAL_FALLBACK || 'true' }}
          # Use GitHub's built-in token for same-user repositories, or custom token for cross-user access
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_GITHUB_TOKEN: ${{ secrets.RESUME_GITHUB_TOKEN }}
        run: npm run build
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
